cd project/static/
mkdir lib
cd lib/
wget https://github.com/twbs/bootstrap/releases/download/v4.0.0-beta/bootstrap-4.0.0-beta-dist.zip
apt install unzip
unzip bootstrap-4.0.0-beta-dist.zip
rm bootstrap-4.0.0-beta-dist.zip
wget https://code.jquery.com/jquery-3.2.1.slim.min.js
wget https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js
